FROM vyahello/yfox-base:0.2.0
LABEL metadata="Main image for YFox blog" \
      version=1.0.1 \
      maintainer="Volodymyr Yahello <vjagello93@gmail.com>"
WORKDIR blog/
COPY server server
COPY requirements-yfox.txt yfox.py ./
RUN pip install --no-cache-dir -r requirements-yfox.txt && \
    rm requirements-yfox.txt
ENTRYPOINT python yfox.py
