#!/bin/bash


run_tests(){
    local trash='.pytest_cache'

    echo '--------------------------------------------------------------------------------'
    echo '------------------------------ Running unitests --------------------------------'
    echo '--------------------------------------------------------------------------------'
    
    pytest -v

    [ -d "$trash" ] && echo "removing $trash unitests trash" && rm -rf ${trash} && echo "environment is cleared"

}

run_tests
